apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: wavefront-collector-control-plane
  namespace: wavefront-collector
  labels:
    k8s-app: wavefront-collector-control-plane
    name: wavefront-collector-control-plane
spec:
  selector:
    matchLabels:
      k8s-app: wavefront-collector-control-plane
  template:
    metadata:
      labels:
        k8s-app: wavefront-collector-control-plane
      annotations:
        installation-method: manual
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingRequiredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node.alpha.kubernetes.io/role
                operator: Exists
              - key: node-role.kubernetes.io/master
                operator: Exists

      serviceAccountName: wavefront-collector

      containers:
      - name: wavefront-collector-control-plane
        image: projects.registry.vmware.com/tanzu_observability/kubernetes-collector:1.8.0
        imagePullPolicy: IfNotPresent
        command:
        - /wavefront-collector
        - --daemon=true
        - --config-file=/etc/collector/collector.yaml
        volumeMounts:
        - name: procfs
          mountPath: /host/proc
          readOnly: true
        - mountPath: /etc/collector/
          name: collector-config
          readOnly: true
        env:
        - name: HOST_PROC
          value: /host/proc
        - name: POD_NODE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        - name: POD_NAMESPACE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: INSTALLATION_METHOD
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.annotations['installation-method']
      volumes:
      - name: procfs
        hostPath:
          path: /proc
      - name: collector-config
        configMap:
          name: collector-config
